#!/usr/bin/env bash
# scripts/get-fonts.sh
#
# Downloads the Claude Design typography (Fraunces + Newsreader + JetBrains
# Mono) as self-hostable variable woff2 files, then writes a `fonts.css`
# right next to them in `public/fonts/` so the @font-face URLs can stay
# **relative** (`url(./<hash>.woff2)`). Relative URLs resolve correctly
# whether the site is served from the root or a sub-path (GitHub Pages
# project pages live under `/<repo>/…`), so we don't need to bake any
# base prefix in.
#
# Idempotent — rerun any time Google rev's the file hashes; this script
# overwrites every file it owns.
#
# Requires only: bash, curl, awk, sed, grep. No Python, no pyftsubset,
# no node — Google already subsets and woff2-compresses for us; we just
# mirror what they serve.
#
# Spec: see decisions/ADR-025-self-hosted-claude-design-fonts in the
# Obsidian vault. Supersedes ADR-023 (the CDN stopgap).

set -euo pipefail
cd "$(dirname "$0")/.."

# Same URL the Claude Design prototype uses (Fraunces with SOFT + opsz
# axes, Newsreader with opsz, JetBrains Mono at 400/500). Keep in
# lock-step with the prototype.
CSS_URL='https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT@0,9..144,300..700,0..100;1,9..144,300..700,0..100&family=Newsreader:ital,opsz,wght@0,6..72,400..600;1,6..72,400..600&family=JetBrains+Mono:wght@400;500&display=swap'

# Modern Chrome UA so Google serves variable woff2 (not legacy ttf/woff).
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

OUT_DIR='public/fonts'
CSS_OUT='public/fonts/fonts.css'

mkdir -p "$OUT_DIR"

TMP_CSS=$(mktemp)
trap 'rm -f "$TMP_CSS"' EXIT

echo "Fetching Google Fonts CSS..."
curl -fsSL -A "$UA" "$CSS_URL" > "$TMP_CSS"

# Extract every gstatic.com woff2 URL, dedup while preserving CSS order.
URLS=$(grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2' "$TMP_CSS" | awk '!seen[$0]++')
COUNT=$(echo "$URLS" | wc -l | tr -d ' ')

echo "Downloading $COUNT font files into $OUT_DIR/ ..."
for url in $URLS; do
  fname=$(basename "$url")
  printf '  %s\n' "$fname"
  curl -fsSL -o "$OUT_DIR/$fname" "$url"
done

echo "Writing $CSS_OUT ..."
# Build one sed substitution per URL → relative ./<file>. Relative paths
# resolve against the CSS file's location, which here is
# /<base>/fonts/fonts.css — so ./<hash>.woff2 lands on
# /<base>/fonts/<hash>.woff2 regardless of what <base> is.
SED_EXPR=''
for url in $URLS; do
  fname=$(basename "$url")
  escaped=$(printf '%s' "$url" | sed -e 's/[.\/&]/\\&/g')
  SED_EXPR="${SED_EXPR}s|${escaped}|./${fname}|g
"
done

{
  cat <<'HEADER'
/* public/fonts/fonts.css — self-hosted variable woff2 for Fraunces +
 * Newsreader + JetBrains Mono.
 *
 * Generated by scripts/get-fonts.sh from the Claude Design prototype's
 * exact Google Fonts URL. Rerun the script any time Google rev's their
 * CDN; this file + sibling *.woff2 files are both regenerated together.
 *
 * Lives in `public/fonts/` (NOT `src/styles/`) so the @font-face URLs
 * can stay relative (`url(./<hash>.woff2)`). Relative URLs work
 * regardless of deploy base path — important for GitHub Pages project
 * pages, which serve under `/<repo>/`. Base.astro links this file
 * via `<link href={`${BASE_URL}fonts/fonts.css`}>`.
 *
 * No network at request time — visitor browsers fetch
 * /<base>/fonts/*.woff2 from your origin. See ADR-008 (web fonts
 * allowed, self-host required), ADR-023 (Google Fonts CDN stopgap,
 * superseded), ADR-025 (this file).
 */

HEADER
  sed -E "$SED_EXPR" "$TMP_CSS"
} > "$CSS_OUT"

echo
echo "Done. $COUNT files in $OUT_DIR/:"
ls -la "$OUT_DIR" | tail -n +2
echo
echo "$CSS_OUT references ./<hash>.woff2 (relative) — no runtime third"
echo "party, no base-path coupling."
